# Generated by Django 5.2.8 on 2025-11-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('construcao', 'Construção'), ('jardinagem', 'Jardinagem'), ('cozinha', 'Cozinha'), ('oficina_mecanica', 'Oficina Mecânica'), ('limpeza', 'Limpeza'), ('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('pintura', 'Pintura'), ('ferramentas_manuais', 'Ferramentas Manuais'), ('ferramentas_eletricas', 'Ferramentas Elétricas'), ('automotiva', 'Automotiva'), ('eventos', 'Eventos'), ('mudanca', 'Mudança'), ('outros', 'Outros')], max_length=50),
        ),
    ]
