# Generated by Django 5.2.8 on 2025-11-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='city',
            field=models.CharField(blank=True, help_text='Cidade - ex: São Paulo, Rio de Janeiro', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='state',
            field=models.CharField(blank=True, help_text='Estado (UF) - ex: SP, RJ, MG', max_length=2, null=True),
        ),
    ]
