# Generated by Django 5.2.8 on 2025-11-25 20:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_tool_city_tool_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
